### ISSUE TITLE
Write a report.

### ISSUE THREAD

**Issue by RokIvansek** [ptrus/vietoris_rips_image_classification#5]

**Comment by RokIvansek** [comment]
I found a cool template for our report here:
http://www.latextemplates.com/template/programming-coding-assignment
I added the .tex and .pdf file to our repository. Please look at it an tell me what you think. Note that for the moment the report still contains a lot of examples and lorem ipsum text.

**Comment by adolenc** [comment]
I've added a bunch of TODOs roughly specifying what still needs to be written. I will work on "obtaining/preprocessing data" and "computational complexity" tonight.

It is completely possible that I missed something, so don't hesitate to add it in as you see fit.
